version: "3"
services:
    ws:
      image: apache
      build: .
      container_name: slimphp-container
      ports:
        - "8094:80"
      volumes:
        - .:/var/www/html
      network_mode: bridge
    bd:
      image: mariadb:latest
      build:
        context: data/mysql/
        dockerfile: dockerfile
      container_name: db_slim
      restart: always
      ports:
      - "3306:3306"
      environment:
      - MYSQL_DATABASE=DB_SLIM
      - MYSQL_USER=user_slim
      - MYSQL_PASSWORD=pass_slim
      - MYSQL_ROOT_PASSWORD=root
